apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-service
spec:
  selector:
    app: paymybuddy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
